import type { User, Listing, TransferRequest } from './types';

// Mock users
export const mockUsers: Record<string, User> = {
  'user1': {
    id: 'user1',
    name: 'Sophie Martin',
    email: 'sophie.martin@ghu.fr',
    role: 'agent',
    service: 'Cardiologie',
    uf: 'UF Médecine',
    site: 'APHP Hôpital Cochin'
  },
  'user2': {
    id: 'user2',
    name: 'Pierre Dubois',
    email: 'pierre.dubois@ghu.fr',
    role: 'agent',
    service: 'Urgences',
    uf: 'UF Urgences',
    site: 'APHP Hôpital européen Georges-Pompidou (HEGP)'
  },
  'user3': {
    id: 'user3',
    name: 'Claire Bernard',
    email: 'claire.bernard@ghu.fr',
    role: 'achat',
    service: 'Service Achat',
    uf: 'UF Administration',
    site: 'Institut Mutualiste Montsouris'
  },
  'user4': {
    id: 'user4',
    name: 'Thomas Leroy',
    email: 'thomas.leroy@ghu.fr',
    role: 'admin',
    service: 'Administration',
    uf: 'UF Administration',
    site: 'Groupe Hospitalier Paris Saint-Joseph'
  }
};

// Mock current user (agent by default, can be changed)
export let currentUser: User = mockUsers['user1'];

export const setCurrentUser = (userId: string) => {
  if (mockUsers[userId]) {
    currentUser = mockUsers[userId];
  }
};

// Mock listings
export const mockListings: Listing[] = [
  {
    id: 'ann1',
    title: 'Bureau médical avec rangements',
    description: 'Bureau en bois massif avec 3 tiroirs, très bon état. Utilisé dans un cabinet médical. Dimensions: 150x80cm. Inclut un caisson mobile à roulettes.',
    category: 'mobilier_bureau',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1688578735122-f37256f1b8b0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 2,
    location: 'Bâtiment C, 3ème étage',
    site: 'APHP Hôpital Cochin',
    uf: 'UF Médecine',
    service: 'Cardiologie',
    createdAt: new Date('2026-03-20'),
    updatedAt: new Date('2026-03-20'),
    status: 'published',
    authorId: 'user1',
    author: mockUsers['user1'],
    dimensions: '150x80x75cm',
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  },
  {
    id: 'ann2',
    title: 'Fauteuil roulant manuel standard',
    description: 'Fauteuil roulant manuel, parfait état de fonctionnement. Révision complète effectuée en janvier 2026. Assise confortable, freins en bon état.',
    category: 'equipement_medical',
    condition: 'excellent',
    photos: ['https://images.unsplash.com/photo-1641877492086-771bc14a8e5e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment A, RDC',
    site: 'APHP Hôpital européen Georges-Pompidou (HEGP)',
    uf: 'UF Urgences',
    service: 'Urgences',
    createdAt: new Date('2026-03-22'),
    updatedAt: new Date('2026-03-22'),
    status: 'published',
    authorId: 'user2',
    author: mockUsers['user2'],
    contact: 'pierre.dubois@ghu.fr - Poste 1234'
  },
  {
    id: 'ann3',
    title: 'Écrans PC Dell 24 pouces',
    description: 'Lot de 3 écrans Dell 24 pouces, résolution Full HD. Parfait pour bureaux administratifs ou secrétariats. Câbles inclus.',
    category: 'equipement_informatique',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1595303526913-c7037797ebe7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxEZWxsJTIwMjQlMjBpbmNoJTIwbW9uaXRvciUyMHNjcmVlbiUyMHdoaXRlfGVufDF8fHx8MTc3NDc4NjE3OXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral'],
    quantity: 3,
    location: 'Bâtiment B, 2ème étage',
    site: 'Institut Mutualiste Montsouris',
    uf: 'UF Administration',
    service: 'Informatique',
    createdAt: new Date('2026-03-18'),
    updatedAt: new Date('2026-03-18'),
    status: 'reserved',
    authorId: 'user1',
    author: mockUsers['user1'],
    dimensions: '24 pouces (61cm)',
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  },
  {
    id: 'ann4',
    title: 'Lit médicalisé électrique',
    description: 'Lit médicalisé électrique avec commande filaire, hauteur variable. Bon état général, quelques traces d\'usage mineures. Matelas non inclus.',
    category: 'mobilier_medical',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1758653500620-1c9fd03f3d1b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment C, 1er étage',
    site: 'Groupe Hospitalier Paris Saint-Joseph',
    uf: 'UF Médecine',
    service: 'Gériatrie',
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-15'),
    status: 'reserved',
    authorId: 'user2',
    author: mockUsers['user2'],
    dimensions: '200x90x50-80cm (hauteur variable)',
    contact: 'pierre.dubois@ghu.fr - Poste 1234'
  },
  {
    id: 'ann5',
    title: 'Armoire de rangement métallique',
    description: 'Grande armoire métallique à 4 portes, idéale pour stockage de dossiers ou matériel. Structure solide, quelques rayures superficielles.',
    category: 'materiel_stockage',
    condition: 'fair',
    photos: ['https://images.unsplash.com/photo-1769092992555-42c231deff34?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment A, 2ème étage',
    site: 'Institut médico-légal de Paris',
    uf: 'UF Administration',
    service: 'Archives',
    createdAt: new Date('2026-03-25'),
    updatedAt: new Date('2026-03-25'),
    status: 'published',
    authorId: 'user1',
    author: mockUsers['user1'],
    dimensions: '180x90x45cm',
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  },
  {
    id: 'ann6',
    title: 'Chariot de soins médical',
    description: 'Chariot à 3 plateaux sur roulettes, très pratique pour transporter matériel et médicaments. Nettoyé et désinfecté.',
    category: 'equipement_medical',
    condition: 'excellent',
    photos: ['https://images.unsplash.com/photo-1723233606719-727bd269451e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 2,
    location: 'Bâtiment B, 1er étage',
    site: 'APHP Hôpital Necker Enfants malades',
    uf: 'UF Chirurgie',
    service: 'Bloc opératoire',
    createdAt: new Date('2026-03-21'),
    updatedAt: new Date('2026-03-21'),
    status: 'published',
    authorId: 'user2',
    author: mockUsers['user2'],
    dimensions: '80x50x90cm',
    contact: 'pierre.dubois@ghu.fr - Poste 1234'
  },
  {
    id: 'ann7',
    title: 'Chaises de bureau ergonomiques',
    description: 'Lot de 4 chaises de bureau avec réglage hauteur et dossier inclinable. Très confortables, utilisées dans une salle de réunion. Revêtement en tissu noir.',
    category: 'mobilier_bureau',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1771147372627-7fffe86cf00b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 4,
    location: 'Bâtiment A, 4ème étage',
    site: 'Groupe Hospitalier Nord Essonne',
    uf: 'UF Administration',
    service: 'Direction',
    createdAt: new Date('2026-03-24'),
    updatedAt: new Date('2026-03-24'),
    status: 'published',
    authorId: 'user1',
    author: mockUsers['user1'],
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  },
  {
    id: 'ann8',
    title: 'Setup informatique complet',
    description: 'Configuration complète : unité centrale Dell, écran 27 pouces, clavier et souris sans fil. Idéal pour poste administratif. Windows 11 Pro installé.',
    category: 'equipement_informatique',
    condition: 'excellent',
    photos: ['https://images.unsplash.com/photo-1646759967491-1f291f471134?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment B, 3ème étage',
    site: 'Gustave Roussy',
    uf: 'UF Administration',
    service: 'Ressources Humaines',
    createdAt: new Date('2026-03-26'),
    updatedAt: new Date('2026-03-26'),
    status: 'published',
    authorId: 'user2',
    author: mockUsers['user2'],
    contact: 'pierre.dubois@ghu.fr - Poste 1234'
  },
  {
    id: 'ann9',
    title: 'Armoire pharmacie vitrée',
    description: 'Armoire murale avec porte vitrée et serrure. Parfaite pour stockage sécurisé de médicaments. 3 étagères intérieures réglables en hauteur.',
    category: 'materiel_stockage',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1715520530023-cc8a1b2044ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment C, 2ème étage',
    site: 'Hôpital CHI de Poissy Saint-Germain-en-Laye',
    uf: 'UF Médecine',
    service: 'Oncologie',
    createdAt: new Date('2026-03-23'),
    updatedAt: new Date('2026-03-23'),
    status: 'published',
    authorId: 'user1',
    author: mockUsers['user1'],
    dimensions: '80x60x20cm',
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  },
  {
    id: 'ann10',
    title: 'Imprimante laser couleur HP',
    description: 'Imprimante multifonction laser couleur HP LaserJet. Impression, copie, scan. Réseau Ethernet et WiFi. Cartouches neuves incluses.',
    category: 'equipement_informatique',
    condition: 'excellent',
    photos: ['https://images.unsplash.com/photo-1613395450289-e560907d9308?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment A, 1er étage',
    site: 'Centre Hospitalier de Chartres',
    uf: 'UF Administration',
    service: 'Comptabilité',
    createdAt: new Date('2026-03-27'),
    updatedAt: new Date('2026-03-27'),
    status: 'published',
    authorId: 'user2',
    author: mockUsers['user2'],
    contact: 'pierre.dubois@ghu.fr - Poste 1234'
  },
  {
    id: 'ann11',
    title: 'Brancard de transport',
    description: 'Brancard de transport sur roulettes avec matelas. Hauteur réglable, freins aux 4 roues. Entièrement désinfecté et révisé.',
    category: 'equipement_medical',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1758206524196-838bdb43ab20?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment A, RDC',
    site: 'APHP Hôpital européen Georges-Pompidou (HEGP)',
    uf: 'UF Urgences',
    service: 'Urgences',
    createdAt: new Date('2026-03-19'),
    updatedAt: new Date('2026-03-19'),
    status: 'published',
    authorId: 'user2',
    author: mockUsers['user2'],
    dimensions: '190x70x90cm',
    contact: 'pierre.dubois@ghu.fr - Poste 1234'
  },
  {
    id: 'ann12',
    title: 'Table de réunion modulable',
    description: 'Grande table de réunion rectangulaire en stratifié blanc. Surface résistante, pieds métalliques. Peut accueillir 8 personnes confortablement.',
    category: 'mobilier_bureau',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1758711516684-e7a87556015e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment B, 4ème étage',
    site: 'APHP Hôpital Cochin',
    uf: 'UF Administration',
    service: 'Formation',
    createdAt: new Date('2026-03-17'),
    updatedAt: new Date('2026-03-17'),
    status: 'published',
    authorId: 'user1',
    author: mockUsers['user1'],
    dimensions: '240x100x75cm',
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  },
  {
    id: 'ann13',
    title: 'Tabouret médical réglable',
    description: 'Tabouret médical pivotant avec dossier et réglage en hauteur. Assise en skai facilement nettoyable. Base à 5 roulettes pour une stabilité optimale.',
    category: 'mobilier_medical',
    condition: 'excellent',
    photos: ['https://images.unsplash.com/photo-1650167202574-d8448576292a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 3,
    location: 'Bâtiment C, 1er étage',
    site: 'Institut Mutualiste Montsouris',
    uf: 'UF Médecine',
    service: 'Consultations',
    createdAt: new Date('2026-03-16'),
    updatedAt: new Date('2026-03-16'),
    status: 'published',
    authorId: 'user1',
    author: mockUsers['user1'],
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  },
  {
    id: 'ann14',
    title: 'Bureau direction en L',
    description: 'Bureau d\'angle en forme de L, plateau stratifié aspect noyer. Grande surface de travail, passe-câbles intégré. Trois tiroirs avec serrure.',
    category: 'mobilier_bureau',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1621926187610-946177e44cca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment A, 5ème étage',
    site: 'Groupe Hospitalier Paris Saint-Joseph',
    uf: 'UF Administration',
    service: 'Direction Générale',
    createdAt: new Date('2026-03-14'),
    updatedAt: new Date('2026-03-14'),
    status: 'published',
    authorId: 'user2',
    author: mockUsers['user2'],
    dimensions: '160x160x75cm',
    contact: 'pierre.dubois@ghu.fr - Poste 1234'
  },
  {
    id: 'ann15',
    title: 'Lit hospitalier électrique premium',
    description: 'Lit médicalisé haut de gamme avec télécommande sans fil. 4 moteurs électriques, garde-corps escamotables, roulettes directionnelles avec freins centralisés.',
    category: 'mobilier_medical',
    condition: 'excellent',
    photos: ['https://images.unsplash.com/photo-1710074213379-2a9c2653046a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment C, 3ème étage',
    site: 'APHP Hôpital Necker Enfants malades',
    uf: 'UF Médecine',
    service: 'Soins Intensifs',
    createdAt: new Date('2026-03-13'),
    updatedAt: new Date('2026-03-13'),
    status: 'published',
    authorId: 'user1',
    author: mockUsers['user1'],
    dimensions: '210x95x40-90cm',
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  },
  {
    id: 'ann16',
    title: 'Classeur mobile sur roulettes',
    description: 'Meuble de classement mobile 3 tiroirs, structure métallique robuste. Finition anti-rayures. Serrure intégrée pour sécuriser les documents.',
    category: 'materiel_stockage',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1569235186275-626cb53b83ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 2,
    location: 'Bâtiment B, 2ème étage',
    site: 'Groupe Hospitalier Nord Essonne',
    uf: 'UF Administration',
    service: 'Secrétariat médical',
    createdAt: new Date('2026-03-12'),
    updatedAt: new Date('2026-03-12'),
    status: 'published',
    authorId: 'user2',
    author: mockUsers['user2'],
    dimensions: '60x40x65cm',
    contact: 'pierre.dubois@ghu.fr - Poste 1234'
  },
  {
    id: 'ann17',
    title: 'Armoire vestiaire métallique 2 portes',
    description: 'Vestiaire métallique robuste pour bureaux ou zones de pause. Fermeture par moraillon, état général très correct.',
    category: 'materiel_stockage',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 2,
    location: 'Bâtiment D, RDC',
    site: 'APHP Hôpital Cochin',
    uf: 'UF Administration',
    service: 'Logistique',
    createdAt: new Date('2026-03-11'),
    updatedAt: new Date('2026-03-11'),
    status: 'published',
    authorId: 'user1',
    author: mockUsers['user1'],
    dimensions: '180x80x50cm',
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  },
  {
    id: 'ann18',
    title: 'Échographe portable de consultation',
    description: 'Échographe portable avec chariot compact, idéal pour consultations et examens rapides. Fonctionnel et révisé.',
    category: 'equipement_medical',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1581595219315-a187dd40c322?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment E, 2ème étage',
    site: 'Institut Mutualiste Montsouris',
    uf: 'UF Imagerie',
    service: 'Consultations',
    createdAt: new Date('2026-03-10'),
    updatedAt: new Date('2026-03-10'),
    status: 'published',
    authorId: 'user2',
    author: mockUsers['user2'],
    contact: 'pierre.dubois@ghu.fr - Poste 1234'
  },
  {
    id: 'ann19',
    title: 'Bureau assis-debout électrique',
    description: 'Poste de travail motorisé avec mémoire de hauteur et plateau chêne clair. Très bon état, usage administratif.',
    category: 'mobilier_bureau',
    condition: 'excellent',
    photos: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment F, 4ème étage',
    site: 'Gustave Roussy',
    uf: 'UF Administration',
    service: 'Qualité',
    createdAt: new Date('2026-03-09'),
    updatedAt: new Date('2026-03-09'),
    status: 'published',
    authorId: 'user1',
    author: mockUsers['user1'],
    dimensions: '160x80x70-120cm',
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  },
  {
    id: 'ann20',
    title: 'Laptop Dell Latitude 15 pouces',
    description: 'Ordinateur portable professionnel avec station d’accueil, clavier rétroéclairé et chargeur. Reconditionné en interne.',
    category: 'equipement_informatique',
    condition: 'excellent',
    photos: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 2,
    location: 'Bâtiment G, 3ème étage',
    site: 'APHP Hôpital Necker Enfants malades',
    uf: 'UF Administration',
    service: 'Informatique',
    createdAt: new Date('2026-03-08'),
    updatedAt: new Date('2026-03-08'),
    status: 'published',
    authorId: 'user2',
    author: mockUsers['user2'],
    contact: 'pierre.dubois@ghu.fr - Poste 1234'
  },
  {
    id: 'ann21',
    title: 'Fauteuil de prélèvement médical',
    description: 'Fauteuil ergonomique pour soins ambulatoires, inclinable avec accoudoirs réglables. Très bon maintien et sellerie propre.',
    category: 'mobilier_medical',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1516549655169-df83a0774514?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment H, 1er étage',
    site: 'Groupe Hospitalier Paris Saint-Joseph',
    uf: 'UF Soins',
    service: 'Hôpital de jour',
    createdAt: new Date('2026-03-07'),
    updatedAt: new Date('2026-03-07'),
    status: 'published',
    authorId: 'user1',
    author: mockUsers['user1'],
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  },
  {
    id: 'ann22',
    title: 'Lit d’examen à hauteur variable',
    description: 'Lit d’examen médical avec dossier relevable et réglage électrique de hauteur. Revêtement facilement désinfectable.',
    category: 'mobilier_medical',
    condition: 'excellent',
    photos: ['https://images.unsplash.com/photo-1584515933487-779824d29309?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment I, 2ème étage',
    site: 'Centre Hospitalier de Chartres',
    uf: 'UF Médecine',
    service: 'Consultations spécialisées',
    createdAt: new Date('2026-03-06'),
    updatedAt: new Date('2026-03-06'),
    status: 'published',
    authorId: 'user2',
    author: mockUsers['user2'],
    dimensions: '190x70x55-90cm',
    contact: 'pierre.dubois@ghu.fr - Poste 1234'
  },
  {
    id: 'ann23',
    title: 'Écran ultra-large 34 pouces',
    description: 'Moniteur 34 pouces incurvé, idéal pour postes de supervision ou secrétariats multi-applications. Câbles fournis.',
    category: 'equipement_informatique',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment J, 5ème étage',
    site: 'Hôpital CHI de Poissy Saint-Germain-en-Laye',
    uf: 'UF Administration',
    service: 'Pilotage',
    createdAt: new Date('2026-03-05'),
    updatedAt: new Date('2026-03-05'),
    status: 'published',
    authorId: 'user1',
    author: mockUsers['user1'],
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  },
  {
    id: 'ann24',
    title: 'Scanner documentaire réseau',
    description: 'Scanner de bureau rapide avec chargement automatique, adapté à la numérisation de dossiers patients et archives.',
    category: 'equipement_informatique',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1516321318423-f06f85e504b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 1,
    location: 'Bâtiment K, 2ème étage',
    site: 'APHP Hôpital européen Georges-Pompidou (HEGP)',
    uf: 'UF Administration',
    service: 'Archives médicales',
    createdAt: new Date('2026-03-04'),
    updatedAt: new Date('2026-03-04'),
    status: 'published',
    authorId: 'user2',
    author: mockUsers['user2'],
    contact: 'pierre.dubois@ghu.fr - Poste 1234'
  },
  {
    id: 'ann25',
    title: 'Tablette de visite médicale renforcée',
    description: 'Tablette durcie avec coque de protection, pratique pour mobilité et accès rapide aux dossiers en service.',
    category: 'autre',
    condition: 'good',
    photos: ['https://images.unsplash.com/photo-1546054454-aa26e2b734c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'],
    quantity: 3,
    location: 'Bâtiment L, 3ème étage',
    site: 'Institut Mutualiste Montsouris',
    uf: 'UF Numérique',
    service: 'Support applicatif',
    createdAt: new Date('2026-03-03'),
    updatedAt: new Date('2026-03-03'),
    status: 'published',
    authorId: 'user1',
    author: mockUsers['user1'],
    contact: 'sophie.martin@ghu.fr - Poste 3421'
  }
];

// Mock requests
export const mockRequests: TransferRequest[] = [
  {
    id: 'req1',
    listingId: 'ann3',
    listing: mockListings.find(a => a.id === 'ann3'),
    requesterId: 'user2',
    requester: mockUsers['user2'],
    destinationService: 'Secrétariat Urgences',
    justification: 'Besoin de remplacer les anciens écrans 19 pouces du secrétariat.',
    createdAt: new Date('2026-03-23'),
    status: 'pending_validation'
  },
  {
    id: 'req2',
    listingId: 'ann4',
    listing: mockListings.find(a => a.id === 'ann4'),
    requesterId: 'user1',
    requester: mockUsers['user1'],
    destinationService: 'Service EHPAD',
    justification: 'Nouveau patient nécessitant un lit médicalisé avec hauteur variable.',
    createdAt: new Date('2026-03-19'),
    status: 'validated',
    decision: {
      validated: true,
      reason: 'Matériel amorti, transfert autorisé.',
      decidedAt: new Date('2026-03-20'),
      decidedBy: 'user3'
    }
  },
  {
    id: 'req3',
    listingId: 'ann1',
    listing: mockListings.find(a => a.id === 'ann1'),
    requesterId: 'user2',
    requester: mockUsers['user2'],
    destinationService: 'Cabinet médecin chef',
    justification: 'Remplacement du mobilier vétuste du cabinet.',
    createdAt: new Date('2026-03-26'),
    status: 'sent'
  }
];
